name: inner_shadow_container
description: A customizable Flutter widget that adds subtle inner shadow effect to containers.
version: 1.0.0

homepage: https://github.com/karanpadaliya/Inner_Shadow_Container
repository: https://github.com/karanpadaliya/Inner_Shadow_Container
issue_tracker: https://github.com/karanpadaliya/Inner_Shadow_Container/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
# Optional: Only add if you're using image assets (e.g. screenshots in README)
# assets:
#   - assets/screenshot.png
