name: inner_shadow_container
description: A customizable Flutter widget to add soft, neumorphic-style inner shadows to containers and UI components.
version: 1.0.1

homepage: https://github.com/karanpadaliya/Inner_Shadow_Container
repository: https://github.com/karanpadaliya/Inner_Shadow_Container
issue_tracker: https://github.com/karanpadaliya/Inner_Shadow_Container/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - flutter-ui
  - container
  - shadow
  - inner-shadow
  - neumorphism

